
[network]
# what interface to setup packet interceptor
#iface = "enx00e04c68004a" #wlp58s0

# trace route from here
edge = "192.168.1.0/24"

[traceroute]
type = "icmp" #icmp|udp|tcp|

[traceroute.tcp]
port = "80"


[redis]
url = "redis://localhost"